import { useEffect, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getAnalytics, analyzeSentiment, startScraper, getHistory, getFavorites } from '../services/api'
import ReviewCard from '../components/ReviewCard'
import Loading from '../components/Loading'

const colors = ['#2c9b78', '#8d8bd5', '#e96c79']
const title = { dashboard: 'Command center', products: 'Product catalog', search: 'Product search', reviews: 'Review library', sentiment: 'Sentiment lab', analytics: 'Analytics studio', trends: 'Trend monitor', scraper: 'Review importer', reports: 'Report center', history: 'Analysis history', favorites: 'Favorites', settings: 'Workspace settings', help: 'Help & documentation' }
const demoCopy = { analytics: 'Compare product performance across every signal.', trends: 'See how customer opinion changes over time.', reports: 'Turn your review intelligence into a shareable summary.', history: 'Every completed analysis, in one place.', favorites: 'Keep your most important products close.', help: 'A practical guide to the SentimentAI workspace.' }

function Empty({ text = 'No data yet.' }) { return <div className="empty-card"><span>◌</span><h3>{text}</h3><p>Run an analysis to populate this workspace.</p></div> }
function SectionHead({ name, action }) { return <div className="section-head"><div><p className="eyebrow">WORKSPACE / {name.toUpperCase()}</p><h1>{title[name] || name}</h1></div>{action}</div> }
function Stats({ overview }) { const items = [['Total products', overview?.total_products || 0, 'catalog'], ['Total reviews', overview?.total_reviews || 0, 'indexed'], ['Positive sentiment', overview?.positive || 0, 'reviews'], ['Negative sentiment', overview?.negative || 0, 'reviews'], ['Average rating', `${overview?.average_rating || 0} / 5`, 'across catalog']]; return <div className="stats">{items.map(([label, value, hint]) => <div className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div> }
function Dashboard({ overview }) { const sentiment = [{ name: 'Positive', value: overview?.positive || 0 }, { name: 'Neutral', value: overview?.neutral || 0 }, { name: 'Negative', value: overview?.negative || 0 }]; return <><SectionHead name="dashboard" action={<span className="status"><i /> Live workspace</span>} /><Stats overview={overview} /><div className="dashboard-grid"><div className="chart-panel"><h3>Sentiment distribution</h3><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={sentiment} dataKey="value" innerRadius={66} outerRadius={96} paddingAngle={4}>{sentiment.map((item, i) => <Cell key={item.name} fill={colors[i]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="legend">{sentiment.map((item, i) => <span key={item.name}><i style={{ background: colors[i] }} />{item.name} <b>{item.value}</b></span>)}</div></div><div className="chart-panel"><h3>Sentiment balance</h3><ResponsiveContainer width="100%" height={260}><BarChart data={sentiment}><CartesianGrid vertical={false} stroke="#e8eef7" /><XAxis dataKey="name" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#5a9be8" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></div></> }
function ProductCard({ product, onAnalyze, onFavorite }) { return <article className="product-card"><div className="product-art">{product.name.slice(0, 2).toUpperCase()}</div><div className="product-info"><div className="product-row"><h3>{product.name}</h3><button className="heart" onClick={() => onFavorite(product)}>♡</button></div><p>{product.source || 'Demo catalog'}</p><div className="product-meta"><b>★ {product.rating || '—'}</b><span>{product.review_count || 0} reviews</span></div><div className="card-actions"><button onClick={() => onAnalyze(product.name)}>Analyze</button><a className="quiet-link" href={`/products/${product._id}`}>Details</a><button className="quiet" onClick={() => onFavorite(product)}>Favorite</button></div></div></article> }
function Products({ products, onAnalyze, onFavorite, search = false }) { const [query, setQuery] = useState(''); const filtered = products.filter(item => item.name.toLowerCase().includes(query.toLowerCase())); return <><SectionHead name={search ? 'search' : 'products'} action={<button className="primary" onClick={() => onAnalyze('iPhone 15')}>+ Analyze product</button>} /><div className="filterbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder={search ? 'Search by name, keyword, or product ID' : 'Filter product catalog'} /><select><option>Sort: Latest</option><option>Sort: Rating</option><option>Sort: Review count</option></select><button className="quiet-btn" onClick={() => setQuery('')}>Clear</button></div><div className="product-grid">{filtered.length ? filtered.map(product => <ProductCard key={product._id || product.name} product={product} onAnalyze={onAnalyze} onFavorite={onFavorite} />) : <Empty text="No matching products" />}</div></> }
function Reviews({ reviews }) { const [query, setQuery] = useState(''); const [sentiment, setSentiment] = useState('All sentiments'); const filtered = reviews.filter(item => item.text.toLowerCase().includes(query.toLowerCase()) && (sentiment === 'All sentiments' || item.sentiment === sentiment)); return <><SectionHead name="reviews" action={<span className="status">{filtered.length} visible reviews</span>} /><div className="filterbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search review text..." /><select value={sentiment} onChange={e => setSentiment(e.target.value)}><option>All sentiments</option><option>Positive</option><option>Neutral</option><option>Negative</option></select></div><div className="review-grid">{filtered.length ? filtered.map((review, i) => <ReviewCard review={review} key={`${review._id || review.date}-${i}`} />) : <Empty text="No reviews match these filters" />}</div></> }
function SentimentLab() { const [text, setText] = useState('This product is excellent and the quality is amazing.'); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { setResult((await analyzeSentiment(text)).data) } finally { setBusy(false) } }; return <><SectionHead name="sentiment" action={<span className="status">VADER NLP engine</span>} /><div className="lab-grid"><div className="form-panel"><label>Paste a customer review</label><textarea value={text} onChange={e => setText(e.target.value)} rows="8" /><button className="primary" onClick={run} disabled={busy}>{busy ? 'Analyzing...' : '✦ Analyze sentiment'}</button></div>{result ? <div className={`result-panel ${result.sentiment.toLowerCase()}`}><span className="result-icon">{result.sentiment === 'Positive' ? '↗' : result.sentiment === 'Negative' ? '↘' : '→'}</span><p className="eyebrow">MODEL OUTPUT</p><h2>{result.sentiment}</h2><div className="meter"><i style={{ width: `${Math.min(100, Math.abs(result.score) * 100)}%` }} /></div><div className="result-values"><span>Score <b>{result.score}</b></span><span>Polarity <b>{result.polarity}</b></span></div><small>{result.model_note}</small></div> : <Empty text="Your result will appear here" />}</div></> }
function Generic({ name }) { return <><SectionHead name={name} /><div className="feature-banner"><div><p className="eyebrow">INSIGHT WORKSPACE</p><h2>{demoCopy[name] || 'Configure your workspace around the questions that matter.'}</h2><p>Use the controls below to work with live API data, demo imports, and saved analysis records.</p></div><span className="banner-icon">✦</span></div><div className="three-panels"><div><b>Connected data</b><p>API responses stay centralized and reusable across views.</p></div><div><b>Actionable output</b><p>Exportable summaries keep decisions easy to share.</p></div><div><b>Safe demo mode</b><p>Sample data keeps every workflow testable without credentials.</p></div></div></> }
function Scraper({ onAnalyze }) { const [product, setProduct] = useState('iPhone 15'); const [result, setResult] = useState(null); const run = async () => setResult((await startScraper(product)).data); return <><SectionHead name="scraper" /><div className="scraper-panel"><p className="eyebrow">SAFE DEMO IMPORT</p><h2>Bring review data into the workspace</h2><p>Live website scraping is opt-in. This mode uses compliant sample data and never bypasses login, CAPTCHA, or anti-bot controls.</p><div className="inline-form"><input value={product} onChange={e => setProduct(e.target.value)} placeholder="Product name" /><button className="primary" onClick={run}>Start import</button></div>{result && <div className="import-result"><b>Import completed</b><span>{result.reviews_collected} reviews collected for {result.product}</span><button onClick={() => onAnalyze(product)}>Analyze now →</button></div>}</div></> }
function Report({ overview, reviews }) { const download = type => { const content = type === 'json' ? JSON.stringify({ overview, reviews }, null, 2) : ['metric,value', ...Object.entries(overview || {})].join('\n'); const blob = new Blob([content], { type: type === 'json' ? 'application/json' : 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `sentiment-report.${type}`; link.click() }; return <><SectionHead name="reports" action={<div className="button-row"><button onClick={() => download('csv')}>↓ CSV</button><button onClick={() => download('json')}>↓ JSON</button><button onClick={() => window.print()}>Print</button></div>} /><div className="report-preview"><p className="eyebrow">SENTIMENTAI REPORT / {new Date().toLocaleDateString()}</p><h2>Product sentiment summary</h2><Stats overview={overview} /><p>This report summarizes {overview?.total_reviews || 0} analyzed reviews across {overview?.total_products || 0} products. Use the export controls to continue the analysis outside the workspace.</p></div></> }
function Records({ name }) { const [items, setItems] = useState([]); useEffect(() => { (name === 'history' ? getHistory() : getFavorites()).then(response => setItems(response.data[name])).catch(() => setItems([])) }, [name]); return <><SectionHead name={name} action={<span className="status">{items.length} saved records</span>} />{items.length ? <div className="record-list">{items.map(item => <div className="record-row" key={item._id || item.name}><div><b>{item.product || item.name}</b><small>{item.date || item.created_at || 'Saved product'}</small></div><span>{item.sentiment || `★ ${item.rating || 0}`}</span><strong>{item.review_count || ''}</strong></div>)}</div> : <Empty text={name === 'history' ? 'No analysis history yet' : 'No favorite products yet'} />}</> }
function Insights({ name, overview }) { const [data, setData] = useState(null); useEffect(() => { getAnalytics('iPhone 15').then(response => setData(response.data)).catch(() => setData(null)) }, []); const ratings = Object.entries(data?.rating_distribution || {}).map(([rating, count]) => ({ rating: `${rating}★`, count })); const trend = (data?.sentiment_trend || []).map(item => ({ date: item.date.slice(5), score: item.score, rating: item.rating })); return <><SectionHead name={name} action={<span className="status">Live catalog signals</span>} /><Stats overview={overview} /><div className="dashboard-grid"><div className="chart-panel"><h3>{name === 'trends' ? 'Sentiment over time' : 'Rating performance'}</h3><ResponsiveContainer width="100%" height={260}>{name === 'trends' ? <LineChart data={trend}><CartesianGrid vertical={false} stroke="#e8eef7" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Line type="monotone" dataKey="score" stroke="#4b90e9" strokeWidth={3} dot={false} /></LineChart> : <BarChart data={ratings}><CartesianGrid vertical={false} stroke="#e8eef7" /><XAxis dataKey="rating" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" fill="#8d8bd5" radius={[6, 6, 0, 0]} /></BarChart>}</ResponsiveContainer></div><div className="chart-panel"><h3>Keyword frequency</h3><div className="words">{(data?.word_frequency || []).map(item => <span key={item.word}>{item.word} <b>{item.count}</b></span>)}</div></div></div></> }
function Settings() { const [dark, setDark] = useState(localStorage.getItem('sentiment-theme') === 'dark'); const toggle = () => { const next = !dark; setDark(next); localStorage.setItem('sentiment-theme', next ? 'dark' : 'light'); document.documentElement.dataset.theme = next ? 'dark' : 'light' }; return <><SectionHead name="settings" /><div className="settings-grid"><div className="form-panel"><p className="eyebrow">PREFERENCES</p><h2>Workspace appearance</h2><div className="setting-row"><div><b>Dark mode</b><small>Use a low-glare canvas for focused analysis.</small></div><button className={`toggle ${dark ? 'on' : ''}`} onClick={toggle}><i /></button></div><div className="setting-row"><div><b>Notifications</b><small>Show completion messages for imports and analysis.</small></div><input type="checkbox" defaultChecked /></div></div><div className="form-panel"><p className="eyebrow">CONNECTIONS</p><h2>System status</h2><div className="connection"><i /> Flask API <b>Ready</b></div><div className="connection"><i /> Database <b>Demo fallback</b></div><div className="connection"><i /> Sentiment engine <b>VADER</b></div></div></div></> }
function Help() {
	return <>
		<SectionHead name="help" />
		<div className="help-grid">
			<div className="feature-banner">
				<div><p className="eyebrow">GETTING STARTED</p><h2>Search a product, then let the signals lead.</h2><p>Use Product Search to run a safe demo import, Dashboard to compare signals, and Reports to export what you find.</p></div>
				<span className="banner-icon">?</span>
			</div>
			<div className="three-panels">
				<div><b>Demo mode</b><p>Five known products and a generic fallback keep the app usable without marketplace credentials.</p></div>
				<div><b>MongoDB Atlas</b><p>Add MONGO_URI to backend/.env when you are ready to persist records across restarts.</p></div>
				<div><b>Approved scraping</b><p>Only use sources you are allowed to access. Never bypass login or anti-bot controls.</p></div>
			</div>
		</div>
	</>
}
function Home({ overview, products, onAnalyze }) { return <><section className="home-hero"><div><p className="eyebrow">PRODUCT INTELLIGENCE / 01</p><h1>Make every review <em>meaningful.</em></h1><p className="hero-copy">SentimentAI turns customer language into clear signals your team can act on, from the first review to the latest trend.</p><div className="button-row"><button className="primary" onClick={() => onAnalyze('iPhone 15')}>Analyze a product →</button><a className="secondary" href="/dashboard">View dashboard</a></div></div><div className="hero-visual"><div className="hero-ring"><b>72</b><span>sentiment<br />index</span></div><div className="float-note">↑ 18.4%<small>positive momentum</small></div></div></section><Stats overview={overview} /><section className="home-lower"><div><p className="eyebrow">HOW IT WORKS</p><h2>From raw feedback to a sharper point of view.</h2><div className="steps"><div><b>01</b><span>Collect</span><p>Import reviews with safe demo data or your approved source.</p></div><div><b>02</b><span>Understand</span><p>VADER classifies the language behind every rating.</p></div><div><b>03</b><span>Act</span><p>Use trends and comparisons to prioritize what matters.</p></div></div></div><div className="recent-panel"><div className="panel-title"><b>Recent products</b><a href="/products">View all</a></div>{products.slice(0, 4).map(product => <div className="recent-item" key={product.name}><span>{product.name.slice(0, 2).toUpperCase()}</span><b>{product.name}</b><small>{product.review_count || 0} reviews</small></div>)}</div></section></> }

export default function WorkspacePage({ name, overview, products, reviews, onAnalyze, onFavorite }) { if (name === 'home') return <Home overview={overview} products={products} onAnalyze={onAnalyze} />; if (name === 'dashboard') return <Dashboard overview={overview} />; if (name === 'products' || name === 'search' || name === 'product-search') return <Products products={products} onAnalyze={onAnalyze} onFavorite={onFavorite} search={name === 'search' || name === 'product-search'} />; if (name === 'reviews') return <Reviews reviews={reviews} />; if (name === 'sentiment') return <SentimentLab />; if (name === 'scraper') return <Scraper onAnalyze={onAnalyze} />; if (name === 'reports') return <Report overview={overview} reviews={reviews} />; if (name === 'history' || name === 'favorites') return <Records name={name} />; if (name === 'settings') return <Settings />; if (name === 'help') return <Help />; if (name === 'analytics' || name === 'trends') return <Insights name={name} overview={overview} />; return <><SectionHead name={name} /><Empty /></> }
